### ISSUE TITLE
stringTest=long problem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#103]
Labels on the wavelength sliders need to have maxWidth set to prevent this:

![screenshot_144](https://cloud.githubusercontent.com/assets/3046552/12988268/21fb89c0-d0bd-11e5-87ea-1aa8c07beb14.png)

**Comment by pixelzoom** [comment]
Should be limited to the width of the wavelength slider.

**Comment by phet-steele** [comment]
@pixelzoom it is indeed fixed in 1.1.0-rc.1. I don't have permission to close in this repo, so you can (and maybe add the QA team :smile: ).

![colorvisionlong](https://cloud.githubusercontent.com/assets/5863899/12990295/e1431cd6-d0c6-11e5-801e-ea8ff58b04e6.PNG)

**Comment by pixelzoom** [comment]
Thanks @phet-steele. Closing.
