### ISSUE TITLE
remaining 1.1.0 redeploy items

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#105]
Color Vision 1.1.0 has been deployed to the PhET website.  Here are the remaining items.

**Design/Admin**

- [x] Rosetta test (Opening sim to trusted translators for beta)
- [ ] Check teacher tips are up to date
- [ ] Republish primer video

**Comment by ariel-phet** [comment]
Translation up. Primer video taken care of in separate issues. Sim needs teacher tips, will create an issue.
