### ISSUE TITLE
User reported issue: colors/filters

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/color-vision#107]
I am a science teacher in Henrico County Virginia.  I use your programs and simulations constantly in my classroom because their fantastic quality and accuracy!   Thank you so much for creating great products.
 
I would like to point out an error/oversight on your Color Vision Simulation.  My students have just been learning about color light and how we perceive it.  They just learned for instance that white light is made of all 7 colors and the three primary colors are red, green and blue.  We discussed that the color yellow is really made of Red and Green light being reflected into our eyes and that without one or the other, you would not see the objects as yellow. 
 
On your simulation you have the yellow flashlight emitting yellow photons which is fine but I do wish it could appear as green and red photons.  That or show the difference when using the filter.  For instance, when using yellow light and a red filter the color that the person should see would be red because the red filter would absorb green light but allow the red light within yellow to pass through.  Same is true for a green filter, it would appear as yellow light before the filter but the person would see the color as green.  In your simulation however you show that any filter that does not match the color of the light absorbs everything and merely appears black.  I attached some images to show you what I mean below.  The simulation should also show that if you switch these colors and shine a red light through a yellow filter, it should appear red, the yellow filter would allow the red to pass through so that it can still appear yellow when the red light is mixed with green light. 

![image005](https://cloud.githubusercontent.com/assets/5090275/14960388/a63b5912-1051-11e6-8f51-b858a7856d24.jpg)
![image006](https://cloud.githubusercontent.com/assets/5090275/14960392/a9904b36-1051-11e6-80a6-7a482b43c468.jpg)

Thank you for your time with this, I really  liked your simulation but was disappointed when my students went to use it and discovered that the filter systems all made the person see black because the different colors were being absorbed.  It confused them greatly since it was contradictory to what they learned.

**Comment by ariel-phet** [comment]
@oliver-phet we might want to address this issues in the teacher tips.

Although the teacher is correct that the color yellow can be perceived from a mix of red and green, you can have pure yellow light (as the teacher acknowledges) and you can have a filter that acts the way we show (in optics usually called an "optical bandpass filter"). And in fact the filter slider is made to suggest this assumption.

Feel free to put the teacher in touch with me.

**Comment by ariel-phet** [comment]
Wrote the teacher the following

> First of all, thanks for your feedback and your support of the PhET project!
> 
> So you are correct, that from the way our perception works Red and Green light being reflected into our eyes can be perceived as yellow. But of course Yellow light does also exist (wavelengths between 570-590 nm). So your eye can perceive yellow from actually seeing yellow light, or from seeing a mix of Red and Green.
> 
> For the first screen of Color Vision, we have chosen to model the light source as something like a tunable laser, and the filters as "optical bandpass filters" - the main learning goal of the first screen is to get students to realize the a filter (such as looking through yellow cellophane) is subtractive not additive. A common confusion for students is that if they look at the world through a yellow filter the world looks yellow because the filter has *added* that color not because it has subtracted some of the other colors. That is the learning goal we are trying to address with this screen.
> 
> Perhaps you can address your learning goal with the RGB screen and showing how when you remove one of the colors (such as blue) and only red and green photons remain you perceive yellow?
> 
> We will also plan to add some information to the "Teacher Tips" document addressing your concern.
> 
> Thanks!

She responded back

> Thank you for the information!  I really appreciate you taking the time to help with this.  I completely understand what you mean and will just have to adjust the way I introduce the interactive in the future.  

Seems like we should make these model notes in the teacher tips

**Comment by arouinfar** [comment]
I will update the teacher tips to add this to the model notes @ariel-phet. I will probably take care of this over the weekend or early next week, as I'll be traveling the next few days without my computer.

**Comment by ariel-phet** [comment]
@arouinfar sounds good, not a huge rush, so next week is a perfectly reasonable time frame.

Not sure if it is too technical but for the call out for "filter color" in the tips maybe we call that filter color range, or filter bandwidth or such, or make a note in the call out as well.

**Comment by arouinfar** [comment]
Great idea @ariel-phet. Will do!

**Comment by arouinfar** [comment]
Done! Closing.
