### ISSUE TITLE
instrument perceivedColor Property?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#110]
Noted while working on https://github.com/phetsims/phet-io/issues/661#issuecomment-251415582.

Should `perceivedColor` Property in SingleBulbModel be instrumented?  It's created using `addDerivedProperty`, but with not tandem or phetioValueType specified.

**Comment by samreid** [comment]
Instrumented in 3bdb341d8d665a540d96560fd42acfef59130103, closing.
