### ISSUE TITLE
Sim freezes up after 30 minutes of being in a background tab (perhaps DT should be capped)

### ISSUE THREAD

**Issue by samreid** [phetsims/color-vision#115]
BrainPOP reported:

> in certain sims that perform a lot of actions (such as Color Vision's photon spray), if you leave the simulation running in a background tab for a while and come back to it, you get a huge drop in performance or even a temporary freeze as the tab tries to catch up and update the sim. 

I could not find any place in color vision where DT is capped, that may be the cause of the problem.    I told BrainPOP we would discuss whether we can fix this in a maintenance release or if it would be a new major.minor version, and I would let them know our plans within a week.  @ariel-phet and @kathy-phet can you review this issue to help prioritize and delegate?  The main steps would be:

1. Assign a developer or QA to reproduce the problem
2. Assign a developer to test the hypothesis that capping DT solves the problem
3. If that fixes the problem, publish a maintenance release for phet-io color vision version that BrainPOP is using, which is noted in partners.md
4. **Bonus Credit** Assign 2 developers (or an agenda item for next developer meeting) to discuss capping dt in joist so we don't have to handle this on a sim-by-sim basis.  If not handled in Joist, then we would need to add a QA checklist item to make sure the sim behaves OK after the tab has been unselected for 30+ minutes.

The "high priority" label is mainly because this is for a PhET-iO client and because I told them we would report back with plans by Friday May 12.

**Comment by kathy-phet** [comment]
@samreid - I agree we should figure this out as a priority. I would suggest you and @zepumph work on it this week as PhET-iO time, perhaps exchanging your PhET-iO day from Friday to earlier in the week again.  

A few reflections/questions: 
Is the sim trying to spit out a million messages around the photons when you return to it? 
Shouldn't the sim just "freeze" when it is in the background? No messages? No DT? No actions? 
For instrumented properties that send a lot of messages (drags, photons, etc), should we consider having an optional "turn off" command so that turning on events or states doesn't necessarily can send fewer messages? (this thought goes beyond this particular issue for consideration -- and I'm not sure how related it is to this issue). 

Discussion at Tuesday's developer meeting (if appropriate) sounds good to me.

**Comment by samreid** [comment]
@kathy-phet we'll look into it.  My hypothesis is that the sim freezes while in a different tab, but that when the user goes back to the tab, the sim tries to compute how many photons to "retroactively" make.  We often solve this by putting a limit on how big a DT can be.

> Discussion at Tuesday's developer meeting (if appropriate) sounds good to me.

Also, our now pattern is to have developer "core hours" on Mondays and developer meetings on Thursdays--we haven't met on Tuesdays for several months.

**Comment by samreid** [comment]
This problem is easy to reproduce by the following steps:
1. add the following to Sim.stepSimulation
```js
dt = dt * 30; // TODO: don't commit this
```
2. Run color vision.  Tab away for 10-60 seconds, then tab back.  It is frozen for a while.

**Comment by samreid** [comment]
Here is our discussion about capping dt:
https://github.com/phetsims/joist/issues/130

**Comment by samreid** [comment]
Committed a dt cap in the above commit, and tested that it works well in the test harness described in https://github.com/phetsims/color-vision/issues/115#issuecomment-299901680.  Next we should make a maintenance release of the PhET brand sim and the PhET-iO brand sim.  @zepumph have you performed a cherry pick maintenance release before?

**Comment by samreid** [comment]
New production version published here: https://phet-io.colorado.edu/sims/color-vision/1.2.4-phetio/wrappers/index/

I'll create a tasks issue to make sure it is OK before we share it back to BrainPOP.

**Comment by samreid** [comment]
Testing will proceed in https://github.com/phetsims/tasks/issues/837.  On hold until then.

**Comment by zepumph** [comment]
Sorry I just looked at this. I have cherrypicked a maintenance release before, but not for a while. It seems like you were able to do it pretty successfully though. Let me know if you need more.

**Comment by zepumph** [comment]
Unassigning, let me know if I can help at all.

**Comment by ariel-phet** [comment]
@samreid since testing has been completed, assigning back to you. Feel free to close the testing issue if nothing left to do there.

**Comment by samreid** [comment]
I shared this new version to BrainPOP
