### ISSUE TITLE
clean up IO types

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#119]
Similar to https://github.com/phetsims/beers-law-lab/issues/222

**Comment by pixelzoom** [comment]
In addition to the usual missing type expressions...

SingleBulbPhotonBeamIO.js looks like it has a copy-paste error from beers-law-lab:

`45  * Adds a precipitate particle as specified by the phetioID and state.`

**Comment by pixelzoom** [comment]
As with https://github.com/phetsims/beers-law-lab/issues/222, I cleaned up the IO types, but was unable to test because of phetsims/joist#469. Assigning to @samreid to review and test.

**Comment by samreid** [comment]
The changes look good, closing.
