### ISSUE TITLE
incomplete implementation of SingleBulbPhotonBeamIO

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#120]
This looks like trouble in `SingleBulbPhotonBeamIO`:

```js
    /**
     * Serializes an instance.
     * @returns {Object}
     */
    toStateObject: function() {
      return {};
    },

    /**
     * Deserializes an instance.
     * @returns {}
     */
    fromStateObject: function() {
      return {};
    },

    /**
     */
    setValue: function() {
    }
```

**Comment by samreid** [comment]
It looks like those methods are not necessary, we can opt out of the state altogether and still be a container for `addChildInstance`, fixed in preceding commit.  @pixelzoom would you like to review?  Close if all is well.
