### ISSUE TITLE
Questions about utteranceQueue

### ISSUE THREAD

**Issue by samreid** [phetsims/color-vision#122]
While exploring #121 I wanted to investigate having the sim say "the flashlight turned on" when the user presses the button.  I added this code to SingleBulbScreenView.js constructor:

```js
    model.flashlightOnProperty.link( function( flashlightOn ) {
      utteranceQueue.addToBack(flashlightOn ? 'The flashlight turned on.':'The flashlight turned off.');
    } );
```

With VoiceOver on, after it read through the initial pdom, I pushed the button several times, and then it said "the flashlight turned on" and "the flashlight turned off" several times, then would no longer say the message even if I kept pressing the button.  Am I doing this correctly?  Is there a bug or a misunderstanding of how this is supposed to behave?

**Comment by jessegreenberg** [comment]
@samreid I would expect it to say it once for every time you pressed the button. I tested the snippet in the original comment with Safari + VO and I hear it consistently. Were you using Safari or another browser? Did you happen to switch browser tabs? There is a VO bug where all alerts stop if you switch tabs.

**Comment by samreid** [comment]
I was using Chrome Version 66.0.3359.139 (Official Build) (64-bit) and did not switch tabs.  Let me know if you can reproduce the problem on Mac/Chrome, or if you want me to try to reproduce the problem.

**Comment by zepumph** [comment]
For me, version 66.0.3359.139 (Official Build) (64-bit), I added that code to that file and it worked for me consistently. I switched tabs and it still worked as expected.

**Comment by samreid** [comment]
Were you using NVDA?

**Comment by jessegreenberg** [comment]
Still good to know @zepumph, makes a good data point!

**Comment by ariel-phet** [comment]
Removing @samreid assignment for now, as color vision isn't scheduled for work at the moment

**Comment by pixelzoom** [comment]
@jessegreenberg can this be closed, and/or promoted to a common-code issue?  It doesn't seem specific to color-vision.

**Comment by jessegreenberg** [comment]
This can be closed, utteranceQueue has received many changes since this issue, and recently went through QA testing in https://github.com/phetsims/QA/issues/208
