### ISSUE TITLE
Questions about the a11y design doc

### ISSUE THREAD

**Issue by samreid** [phetsims/color-vision#123]
From #121 I had some questions about the design doc.  One part says:

![image](https://user-images.githubusercontent.com/679486/39905144-0fd15fd8-5499-11e8-97b9-c5e08860267d.png)

Why is the last part gray?  Is it added automatically by something?

The next question is about the perceived color. The design doc says:

![image](https://user-images.githubusercontent.com/679486/39905168-30368ef6-5499-11e8-94cf-0d191bb2d4b5.png)

Is is supposed to say (in the pDOM) "The color perceived in the person’s mind with the current light source conditions"?  Should it also say the currently perceived color (if any), or is that going to be somewhere else? 

Assigned to @ariel-phet since he worked on this design document.

**Comment by pixelzoom** [comment]
@jessegreenberg can this be closed, and/or promoted to a common-code issue? It doesn't seem specific to color-vision.

**Comment by jessegreenberg** [comment]
The first question is general, I made an issue to talk about: https://github.com/phetsims/a11y-research/issues/122

The second question is specific to color-vision. But there are no plans to return to this sim in the near future. And when we do, I think everything in the current design doc will require a full dusting off. So going to go ahead and close.
