### ISSUE TITLE
Add alternative input

### ISSUE THREAD

**Issue by jbphet** [phetsims/color-vision#143]
One of the goals for this quarter is to add alternative input to this simulation.

**Comment by jbphet** [comment]
For reference, I used this doc to guide the process, at least initially: https://github.com/phetsims/phet-info/blob/master/doc/alternative-input-quickstart-guide.md.

**Comment by jbphet** [comment]
Reviewed the current state of this at the 8/2/2022 sound design meeting and decided that it is good for now and we may revisit and update once the design of the interactive description is further along.  I'll defer until then.

**Comment by marlitas** [comment]
Alt Input has been added to the sim along with accessible names. Closing!
