### ISSUE TITLE
Add lab coat to head icons

### ISSUE THREAD

**Issue by Luisav1** [phetsims/color-vision#149]
Instead of making regional artwork, we are updating the one file to have a lab coat.

I am assuming the `head.png`, `headFront.png`, and `headIcon.png`.

**Comment by amanda-phet** [comment]
Here are the updated assets for head.png and headFront.png. I still need to make the icon, but wanted to get these to you now so you can try them out and let me know if adjustments need to be made. 
![head](https://github.com/phetsims/color-vision/assets/7852916/e7228f8a-e43e-454e-8691-016684fba925)

![headFront](https://github.com/phetsims/color-vision/assets/7852916/1fa38a50-c8ca-481e-909c-892f75626b48)

**Comment by Luisav1** [comment]
Thanks @amanda-phet, the images are looking good to me!
![image](https://github.com/phetsims/color-vision/assets/52978048/0fd0513e-0eea-4e49-b719-cb579e4869cb)

I don't believe adjustments need to be made but feel free to check it out too as it's updated on main.

**Comment by amanda-phet** [comment]
I didn't realize I uploaded the one with black hair, and might want to switch it to brown. I might also tweak the top layer and how the light shows up on the face.

**Comment by amanda-phet** [comment]
I confirmed that the black hair is fine, and the top layer looks good. SO I think we can close this!
