### ISSUE TITLE
Add dynamic locale

### ISSUE THREAD

**Issue by Luisav1** [phetsims/color-vision#150]
Change the view the use string properties.

**Comment by Luisav1** [comment]
Dynamic locale is added in. There were only 2 strings so it was a quick process. @amanda-phet this is ready for your review if you'd like to take a look!

**Comment by amanda-phet** [comment]
Looks good to me :)

**Comment by amanda-phet** [comment]
Not sure if this is ready to be closed or not, so back to @Luisav1

**Comment by Luisav1** [comment]
Yes, it's ready to be closed, thanks for taking a look at it @amanda-phet!
