### ISSUE TITLE
Add labels to flashlights and sliders (RGB screen)

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/color-vision#152]
From https://github.com/phetsims/color-vision/issues/148 we decided to make the following updates to this sim: 

- [x] Add intermediate tick marks (at 0, 25, 50, 100) but only label the ends 0% and 100%, above and below the track. (You might need to make the track slightly shorter so the thumb doesn't cover the labels) 
- [x] Label the flashlights on the handles, on a semi-transparent white background. Label each one Red, Green, and Blue. 

![image](https://github.com/phetsims/color-vision/assets/7852916/b79e3fb5-f433-496a-a198-c3a308357582)

**Comment by Luisav1** [comment]
@amanda-phet I have updated the sim and this is what it looks like now:
![image](https://github.com/phetsims/color-vision/assets/52978048/4189461b-b830-48bb-8d9d-f46a0e464cff)
Could you review it to ensure everything is looking good? Thanks!

**Comment by amanda-phet** [comment]
The labels look good to me, although the Blue label background doesn't look "centered" on the handle. Can that be moved "down" slightly on the flashlight handle? 

I'm also not sure about the tick marks.. they don't look connected to the slider track. Is there anything we can do about that? I'm not very familiar with sliders, but that's my first impression. I think it's because the slider track has a black stroke around it, so I would play with also giving the tick marks a black stroke if that's possible.

**Comment by Luisav1** [comment]
Thank you for the review!
I moved the blue label down slightly:
![image](https://github.com/phetsims/color-vision/assets/52978048/7403e5fc-9b3b-4af2-a21b-ad6f4f808556)

On the customizing options for tick marks, they are unfortunately limited in the `SliderTick` class. Currently, you can only adjust the tick's length, width, and color.

I tested with setting the track stroke color to white:
![image](https://github.com/phetsims/color-vision/assets/52978048/21624457-2c88-4a4f-a713-3af1b5b2b9ec)

Also, I tried making both the stroke color white and reducing the track width:
![image](https://github.com/phetsims/color-vision/assets/52978048/f43bc71a-ee27-4063-b2ad-8f09b1d3bdee)

@amanda-phet, do you have any preference or suggestions?

**Comment by amanda-phet** [comment]
I got some feedback on this design and the consensus is we like the third one, which is all white and a thinner track.

**Comment by Luisav1** [comment]
Thanks @amanda-phet! I've applied those changes and this is how it looks like now:
![image](https://github.com/phetsims/color-vision/assets/52978048/28b4f93a-219e-4c64-9f83-60ed221981c1)
This issue is ready to be closed.
