### ISSUE TITLE
Create new screenshots

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/color-vision#154]
This sim needs updated screenshots to reflect the new artwork!

**Comment by amanda-phet** [comment]
(This is to be done during the dev test, so not urgent!)

**Comment by KatieWoe** [comment]
Screenshots uploaded above. I didn't see a 1.3.0 branch to add them too, but they are updated on main at least. Thanks to @Nancy-Salpepi for taking the screenshots!

**Comment by marlitas** [comment]
Color Vision is now published and the screenshots were a part of the 1.3 branch. Thanks!
