### ISSUE TITLE
Keyboard dialog missing

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/color-vision#155]
For https://github.com/phetsims/qa/issues/1115 since this sim has alt input shouldn't there be a keyboard dialog?

**Comment by Luisav1** [comment]
Thanks @Nancy-Salpepi! I've added a keyboard dialog.

@amanda-phet, would you like to take a look at this too? I’ve assigned it to you just in case.

**Comment by KatieWoe** [comment]
Keyboard dialog looks good in dev.5
