### ISSUE TITLE
Color sounds aren't continuously smooth

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/color-vision#157]
**Test device**
MacBook Air M1 chip

**Operating System**
14.5

**Browser**
Safari 17.5

**Problem description**
For https://github.com/phetsims/qa/issues/1115, the sound for the colors is a little glitchy. It reminds me of what things used to sound like when I used a tape recorder. @KatieWoe also heard it on her Win11 device. 

**Steps to reproduce**
Here is an example:
1. On the RGB bulbs screen, increase the % of blue (doesn't matter how much)
2. Don't touch anything else--just listen for several seconds

**Visuals**
You should hear what I mean 3 times in this video (~.5, ~3.5, and ~6.5 seconds)

https://github.com/user-attachments/assets/456b5899-d460-4e1b-bb42-0497089b169f

**Comment by marlitas** [comment]
I haven't had a chance to take a look yet, but @kathy-phet would like to know if @jbphet has a quick solution that can be applied here. I will try to look more deeply into the issue tomorrow to get more context.

**Comment by marlitas** [comment]
We ran into https://github.com/phetsims/color-vision/issues/138 which indicates that the sound design for this sim is not completed. I will reach out to @amanda-phet to confirm what the sound plan is for this publication of the sim.

**Comment by marlitas** [comment]
We discussed sound design for this upcoming publication of Color Vision. We would like to only use UI sounds and turn off custom sounds.

Currently the sliders do not have sounds, so I will investigate as to why that is and make sure default sounds are used there. Opening a new issue and closing this one.

**Comment by marlitas** [comment]
I just realized I probably shouldn't close this. I'll re-open and leave as deferred so that it's here when we decide to work on this sim again.
