### ISSUE TITLE
Filter Color and Bulb Color Sliders are deprecated.

### ISSUE THREAD

**Issue by marlitas** [phetsims/color-vision#159]
While investigating UI sound for Color Vision I saw that the GaussianWavelengthSlider used for FilterColor and the WavelengthSlider used for BulbColor are both deprecated. This is probably why they have no default UI sounds. Best thing is to update them to the supported slider classes and use SpectrumSliderTrack instead.

**Comment by marlitas** [comment]
Both usages are now updated and do not use the deprecated WavelengthSlider. 

This required access to options that were not exposed in SpectrumSliderTrack, so I will assign those changes to @jessegreenberg for review as responsible dev of scenery-phet.

**Comment by jessegreenberg** [comment]
New implementation looks great, nice job matching the previous look.

The scenery-phet change makes sense. The wilder example for nested options uses `combineOptions`, and I wasn't sure if that was the way it should be done or if that was just a trivial example. I made https://github.com/phetsims/wilder/issues/8 to learn more. Feel free to leave as is or consult with someone more familiar with `optionize`. 

If you do keep it as is, I think `stroke` and `lineWidth` should be optional (they are currently required).

**Comment by jessegreenberg** [comment]
I noticed this started appearing on CT, a tandem may be required somewhere:

```
color-vision : phet-io-active-fuzz : unbuilt
URL: http://128.138.93.172/continuous-testing/ct-snapshots/1726180626462/phet-io-wrappers/active/?sim=color-vision&locales=*&phetioWrapperDebug=true&fuzz&phetioDebug=true&wrapperContinuousTest=%7B%22test%22%3A%5B%22color-vision%22%2C%22phet-io-active-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1726180626462%22%2C%22timestamp%22%3A1726181088691%7D
ERROR: Uncaught Error: Assertion failed: required tandems must be supplied
STACK: Error: Assertion failed: required tandems must be supplied
    at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1726180626462/assert/js/assert.js:45:13)
    at assert (PhetioObject.ts:216:6)
    at initializePhetioObject (PhetioObject.ts:196:11)
    at  (PhetioDataHandler.ts:104:4)
    at  (PhetioAction.ts:119:4)
    at  (PressListener.ts:340:24)
    at  (DragListener.ts:228:4)
    at  (SliderTrack.ts:162:24)
    at  (SpectrumSliderTrack.ts:55:4)
    at  (SingleBulbScreenView.js:93:32)
    at  (SingleBulbScreen.js:45:15)
    at createView (Screen.ts:309:22)
    at initializeView (Sim
```

**Comment by marlitas** [comment]
> The wilder example for nested options uses combineOptions, and I wasn't sure if that was the way it should be done or if that was just a trivial example. I made https://github.com/phetsims/wilder/issues/8 to learn more.

I read through the Wilder Options patterns, and I don't think CombineOptions is explicitly necessary here. I left it as part of the optionize call and also made stroke and lineWidth optional. 

I also added in tandems to the slider track. I didn't spend too much time worrying about the tandem structure for this, since the upcoming publication does not include phet-io and that is outside of the scope for this publication.

The issue is now ready for QA

**Comment by marlitas** [comment]
CT is now green.

**Comment by KatieWoe** [comment]
Slider sounds are there for dev.5
