### ISSUE TITLE
Interactive highlights for slider thumbs are different sizes

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/color-vision#161]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0

**Browser**
Safari 18.0

**Problem description**
For https://github.com/phetsims/qa/issues/1150, the size of interactive highlights are different for the 2 slider thumbs. Should the thumb for the filter slider be larger, especially since the curve is grabbable ?

**Visuals**
<img width="263" alt="Screenshot 2024-10-09 at 10 51 09 AM" src="https://github.com/user-attachments/assets/5736ce7f-8f9b-48e6-8169-d3c5eb9f2b74">

<img width="263" alt="Screenshot 2024-10-09 at 10 51 35 AM" src="https://github.com/user-attachments/assets/b2c4c687-0ba0-4dda-bcc6-2ddee1765f00">

**Comment by marlitas** [comment]
Fixed in the above commit. Ready to cherry pick!

**Comment by Matthew-Moore240** [comment]
Interactive highlights for sliders still aren't exactly the same size. The filter's highlight looks quite a bit different and much smaller. 
**Side by side**
![image](https://github.com/user-attachments/assets/82412fc6-9ed3-4534-ae9c-9a0ec60220e4)

**Comment by marlitas** [comment]
The bounds were dilated above to match the spacing.

**Comment by Nancy-Salpepi** [comment]
looks great in rc.5!
