### ISSUE TITLE
Update Credits for 1.3.0 release

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/color-vision#162]
For https://github.com/phetsims/qa/issues/1150

Here are the current credits listed:
<img width="579" alt="Screenshot 2024-10-09 at 1 20 12 PM" src="https://github.com/user-attachments/assets/caa9a2e9-932a-430d-bc99-2d39be61692a">

Please add....
For software development: Marla Schulz and Luisa Vargas 
For QA:  Matthew Moore, Ashton Morris, Nancy Salpepi, Kathryn Woessner

Not sure if I missed anyone.

**Comment by marlitas** [comment]
Updated above. Ready for cherry pick!

**Comment by Nancy-Salpepi** [comment]
Credits updated! Closing.
