### ISSUE TITLE
Brain icon is different than in published

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/color-vision#164]
**Test device**
MacBook Air M1 chip

**Operating System**
15.0

**Browser**
Safari 18.0

**Problem description**
For https://github.com/phetsims/qa/issues/1150, the brain icon doesn't show the silhouette of the head/neck until the radio button has keyboard focus or I hover my pointer over it. This is different than in published and seems like a bug to me. I think the radio button is being grayed out when not selected, so we see nothing but the brain/eye. 

**Visuals**
<img width="147" alt="Screenshot 2024-10-11 at 8 04 10 AM" src="https://github.com/user-attachments/assets/f2b89522-d0c8-4bd7-94c6-6293d8fbd770">
<img width="147" alt="Screenshot 2024-10-11 at 8 07 48 AM" src="https://github.com/user-attachments/assets/b86bde9c-faef-4a99-be72-f02a5415cff0">
d770">

Published:
<img width="147" alt="Screenshot 2024-10-11 at 8 04 47 AM" src="https://github.com/user-attachments/assets/1e3bf649-0937-4c3e-a565-76331e06b32b">

**Comment by marlitas** [comment]
This is happening because the background of the button is now white instead of brown. Therefore, when the opacity changes the contrast is even lighter. I adjusted the opacity so that it does not appear as washed out when deselected. Ready to cherry pick.

**Comment by Nancy-Salpepi** [comment]
This looks much better in rc.4! Closing.
