### ISSUE TITLE
OSX Firefox stutters on RGB screen after adjusting sliders

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/color-vision#42]
Testing on firefox on OSX, I noticed that very reliably there will be a stutter a few frames after adjusting any of the sliders. It seems like a frame with an especially long dt gets interjected somehow. The stutter happens before the photons have time to reach the eye. It happens with uncanny consistency in this situation and not in any others that I have noticed.

It also creates a small gap in the photon stream, as is shown in the picture.

![screen shot 2014-06-25 at 9 59 15 am](https://cloud.githubusercontent.com/assets/3193912/3387839/c30d68fe-fc81-11e3-8e0b-32bafe579288.png)

I'd be curious if anyone else can reproduce or has ideas about what is causing it.

**Comment by pixelzoom** [comment]
Unfortunately there's no info in this issue about which version of Firefox and Mac OS X was used to produce the problem.

Testing with Firefox 44.0.2 on Mac OS X 10.11.3, I see no gap in the photon stream.  So closing.
