### ISSUE TITLE
Touch/Mouse area of wavelength sliders

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/color-vision#63]
In interviews, we saw a student wanting to click on the gaussian and the thin portion of the slider the chooses the bulb color. Seems to make sense to make the touch/mouse area extend to these portions of the slider.

**Comment by pixelzoom** [comment]
The `pointerAreasOverTrack` option turned out to be problematic.  See https://github.com/phetsims/scenery-phet/issues/261#issue-172560572 for problems, see https://github.com/phetsims/scenery-phet/issues/261#issuecomment-241761531 for solution.
