### ISSUE TITLE
Slight lag when turning light on and off

### ISSUE THREAD

**Issue by bryo5363** [phetsims/color-vision#75]
Test device: MacBook Pro

Operating System: OSX 10.9.4

Browser: Chrome 36.0.1985.143

Problem description: When turning the light on and off there is a slight lag and the observer still sees the color that was present prior to turning the light off.

Steps to reproduce:
-Open sim
-Turn on filter
-Match photon color to filter color
-Turn on light. 
-Turn off light
-Once the last of the photons have reached the observer, turn the light on again. The observer will register seeing the color even though there is no stream of photons hitting him/her. 
Severity:

Screenshots:
![screen shot 2014-08-28 at 3 39 46 pm](https://cloud.githubusercontent.com/assets/7717368/4083465/e0cd9498-2efb-11e4-8854-85a0e59d9ba9.png)

Troubleshooting information (do not edit):
Name: Color Vision
URL: http://www.colorado.edu/physics/phet/dev/html/color-vision/1.0.0-rc.2/color-vision_en.html
Version: 1.0.0-rc.2
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36
Language: en-US
Window: 941x637
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 4096 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true

**Comment by ariel-phet** [comment]
@bryo5363 can you see if this bug still exists on the published version of the sim (we just made a redeploy to the website)?

**Comment by bryo5363** [comment]
I did not observe the issue on the published version of the sim

**Comment by ariel-phet** [comment]
Excellent, closing
