### ISSUE TITLE
Sim will not open on FireFox 31.0 Win 8

### ISSUE THREAD

**Issue by orejolaphet** [phetsims/color-vision#76]
The sim will not open and every time I attempt to open it on my machine I receive this issue. I am unable to access trouble shooting information.

![cv](https://cloud.githubusercontent.com/assets/5631059/4083598/9950cb06-2efd-11e4-9b43-51178873c47c.PNG)

**Comment by ariel-phet** [comment]
We have never seen an issue or a complaint since publishing, closing
