### ISSUE TITLE
Slow performance and poor rendering on IE9

### ISSUE THREAD

**Issue by bryo5363** [phetsims/color-vision#78]
Test device: MacBook Pro

Operating System: Win 7 64-bit

Browser: IE 9 9.0.8112.16421

Problem description: Performance is quite slow on IE9; rendering of the observer is quite poor

Steps to reproduce:
-open RGB
-Access all sliders. Sim will run slow

Severity:

Screenshots:
![screen shot 2014-08-28 at 4 31 45 pm](https://cloud.githubusercontent.com/assets/7717368/4084045/6dc5fd5c-2f03-11e4-8534-d7ba04ed65f1.png)

Troubleshooting information (do not edit):

Name: Color Vision

URL: http://www.colorado.edu/physics/phet/dev/html/color-vision/1.0.0-rc.2/color-vision_en.html

Version: 1.0.0-rc.2

Features missing: cssgradients, applicationcache, flexbox, cssanimations, csstransforms3d, applicationcache, history, webworkers, websockets, touch, webgl, fullscreen, raf, svgfilters, Float32Array, Float64Array

User Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0)

Window: 1161x533

Pixel Ratio: 1/1

WebGL: unsupported

**Comment by ariel-phet** [comment]
IE9 is no longer supported, rendering is acceptable on FF closing
