### ISSUE TITLE
Slight GC Stutter in photon view

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/color-vision#84]
@aaronsamuel137 there is a sometimes slightly noticeable stutter in the photon view (my guess is from garbage collection). I do not think this issue needs to be addressed for the current release but I want to note it in github for when we do a future release on Scenery 0.2.

**Comment by Luisav1** [comment]
I have tried to reproduce this Windows 11 both on Chrome and FF in main but have not been able to. It seems that this might have been fixed with the updated Scenery common code. Closing.
