### ISSUE TITLE
aliasing of the lines on the "tilted" flashlights

### ISSUE THREAD

**Issue by bryo5363** [phetsims/color-vision#85]
Observed on Windows 8 IE 11.0.9600.17239

![screenshot 3](https://cloud.githubusercontent.com/assets/7717368/4291491/cdaa6b20-3dc4-11e4-9727-069a193c0805.png)

**Comment by ariel-phet** [comment]
This seems like a candidate for mipmapping next time we republish the sim (which will be necessary for translations and such)

**Comment by pixelzoom** [comment]
We should draw the flashlights programmatically.

**Comment by Luisav1** [comment]
The flashlight is now drawn problematically in `FlashlightNode` with the gradient remaining horizontal whenever that flashlight rotates:
![image](https://github.com/phetsims/color-vision/assets/52978048/23176327-9886-4a26-8101-4ca1fd0f4e69)

I did this to follow the flashlight's and their gradients as in the RGB screen:
![image](https://github.com/phetsims/color-vision/assets/52978048/1f9d2751-20ab-4364-99ab-57ff71eddd4e)

The aliasing is no longer present as a result of this.
