### ISSUE TITLE
Teacher Tips for Color Vision

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/color-vision#89]
When we make the HTML5 version teacher tips we should make a note about the sim producing "purple" photons - we understand purple does not appear as a pure color so anything in that appears purple should be interpreted as violet.

**Comment by ariel-phet** [comment]
@phet-steele you had some thoughts on the teacher tips correct? please note them in this issue

**Comment by ariel-phet** [comment]
@arouinfar - Color Vision is quite a popular sim, we should probably get some teacher tips up for this one soon.

**Comment by phet-steele** [comment]
@arouinfar we probably need to say something saying that the girl can see color from photons that don't hit her eye. If the student sees no photons hitting the eye, but only sees photons hitting the forehead, the girl will still see color. This is likely to arise viewing the trailing end of photons after the bulb is turned off, or when the sim is set up so that only a few photons are traveling at a time:
![colorvisionfewphotons](https://cloud.githubusercontent.com/assets/5863899/13119312/c185c850-d565-11e5-9b7f-6d3eab7030e5.PNG)
Color will still be "seen" in this scenario.

**Comment by arouinfar** [comment]
@ariel-phet I can work on the teacher tips this Friday. Thanks for your comment @phet-steele!

**Comment by ariel-phet** [comment]
@arouinfar I mentioned to @phet-steele that probably the way to address this in the tips is that the photons are obviously a model and each "pixel" photon represents many many photons, so even if the pxiel is not hitting the eye the model still assume a beam of photons.

**Comment by arouinfar** [comment]
@ariel-phet I got a pretty good start on this today, and will wrap it up on Monday.

I'm a bit confused about the purple photon issue after reviewing #88. Is the issue that the low-wavelength end of our bulb color slider appears too purple (as opposed to violet) or is it that the white light photons include pinks/purples that are not composed of a single wavelength? Or both?

![image](https://cloud.githubusercontent.com/assets/8419308/13192767/d49a3e80-d72c-11e5-8806-39e1c18ff732.png)       ![image](https://cloud.githubusercontent.com/assets/8419308/13192772/e45860ae-d72c-11e5-8a65-a33a83b208a5.png)

For reference, this page has several pictures of light being dispersed by a prism including the one below
https://people.rit.edu/andpph/exhibit-spectrum.html 
![image](https://cloud.githubusercontent.com/assets/8419308/13192833/6c9e5090-d72d-11e5-84dc-e60bf3274497.png)

To me, the picture above doesn't appear that far off from the colors in our slider.

**Comment by ariel-phet** [comment]
@arouinfar - the summary is that "purple" is not a pure color, purple photons as such do not exist.

see for example https://deron.meranda.us/ruminations/purple/

> We now know that purple can not be a single pure frequency of light as it does not appear in the visible spectrum. But we also know that we can see something which we call purple, and it is definitely not blue or green or even orange. Purple must be something, but what is it exactly? It turns out that what we observe as purple is always a mixture of other colors, usually some form of red and some form of blue. So purple is not pure in that it is not a single color.

So we should mention something in the teacher tips that although some photons may appear purple assume those are representing violet.

In fact, it is likely the the image you used above used the same algorithm of mapping a color photograph to rgb when it was digitized:)...the page I linked shows a more precise representation of the visible spectrum.

**Comment by arouinfar** [comment]
Aaah, got it @ariel-phet. Thanks! 

I'm wrapping up the tips now, and will be uploading them soon.

**Comment by arouinfar** [comment]
Uploaded!
