### ISSUE TITLE
Check for memory leak 

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/color-vision#92]
While at ISTE I noticed that if color vision was up and running for a very long time (over an hour) it would sometimes give an "unresponsive script" warning and freeze in FF. I am curious if there is perhaps a very slow memory leak?

**Comment by pixelzoom** [comment]
I inadvertently had Color Vision open in Chrome during a meeting today for about 2 hours, on the 2nd screen with all 3 lights on.  The sim (and Chrome) were frozen when I returned to it.

**Comment by Luisav1** [comment]
I did some memory tests on main both in Chrome and Firefox in Windows 11.

Chrome - Note that there's 10 min intervals from Snapshot 12 and on:
![image](https://github.com/phetsims/color-vision/assets/52978048/90211935-e13a-4431-8b88-ba5adba3a351)

Firefox:
![image](https://github.com/phetsims/color-vision/assets/52978048/b39c184f-373c-4d43-9f9e-4027579a35ab)

Based on these it seems that there's no more memory leak present. Closing.
