### ISSUE TITLE
In master white light bulb on first screen is not producing multicolored photons

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/color-vision#94]
@aaronsamuel137 when I was demoing color vision I noticed something funky...if I put on the white light bulb on the first screen and use photon view I only get one color. The sim works correctly on our website, but maybe something got broken in master when the sim was outfitted.

**Comment by aaronsamuel137** [comment]
This should be fixed, assigning to @ariel-phet for review.

**Comment by ariel-phet** [comment]
Fixed verified, closing
