### ISSUE TITLE
Check for person-seeing-color-on-photon-view bug

### ISSUE THREAD

**Issue by kathy-phet** [phetsims/color-vision#95]
I just tested the color vision sim that JB posted for metacog, and when I switch to photon-view he sees black always. Bug is only on the first screen. Not sure if it is present in the latest code - but we should check. Metacog likely has bug. 

Here is version: http://www.colorado.edu/physics/phet/dev/html/phet-metacog/0.0.4/color-vision_en.html

**Comment by kathy-phet** [comment]
Here is Troubleshooting information (do not edit):
Name: Color Vision
URL: http://www.colorado.edu/physics/phet/dev/html/phet-metacog/0.0.4/color-vision_en.html
Version: 1.1.0-together.2 2015-05-26 21:57:21 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36
Language: en-US
Window: 1920x971
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"comment":"# color-vision 1.1.0-together.2 Tue May 26 2015 15:57:20 GMT-0600 (Mountain Daylight Time)","assert":{"sha":"903564a25a0f26acdbd334d3e104039864b405ef","branch":"master"},"axon":{"sha":"ed77e70addb76988c671757f53cf2391eafa916a","branch":"master"},"babel":{"sha":"3ef6bce9237080ffa2d92c30d28b2d6f966bddc4","branch":"master"},"brand":{"sha":"b3362651f1d7eddb7f8697d02400472f97f9d140","branch":"master"},"chipper":{"sha":"377a03674f8a73980863910265d64b59201df1ad","branch":"master"},"color-vision":{"sha":"9a1e792e6fbc6a45650bf2957a397e0ac8e9f309","branch":"master"},"dot":{"sha":"494114cf2ad84a3105dd547ea454efc7f7aa0f9b","branch":"master"},"joist":{"sha":"c3a7ef7f7c6fa75de55ab7a5a164ee546c8e9197","branch":"master"},"kite":{"sha":"b915f3b160744e4833d177dc38e74e4cbc912883","branch":"master"},"phet-core":{"sha":"23834d107dc1cb368c00901c76927b712b9caa10","branch":"master"},"phetcommon":{"sha":"bb92c52cd90fdaa0c2a746fea82594afd439b4db","branch":"master"},"scenery":{"sha":"ba2ebc1d2a89ff7391cd138329d19ca08f766a04","branch":"master"},"scenery-phet":{"sha":"8c4d5f81ec257a5a944b3e5082b032ab62965f40","branch":"master"},"sherpa":{"sha":"d81b7bc1eb3d73d01588022677e03cba102c7b3b","branch":"master"},"sun":{"sha":"825b8672c3650e6c214ac11baa51d55e7d1fd021","branch":"master"}}

**Comment by ariel-phet** [comment]
Closing since we have heard nothing about this bug
