### ISSUE TITLE
Add visibility annotations

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/color-vision#97]
In https://github.com/phetsims/tasks/issues/307 we decided that developers should add these to their own sims.

>Consensus: we will leave it up to developers whether to keep things up to date (a) as we go (b) as the sim is republished or (c) before a developer leaves the team.

Since I am about to be leaving, I will try to get this done for color-vision before hand.

**Comment by aaronsamuel137** [comment]
As part of these changes, I turned some attributes into vars that didn't really need to be attributes. However, now I am wondering whether these were needed for together somehow.

Here's the attributes I changed to vars:

In ColorVisionScreenView:
- resetAllButton
- playPauseButton
- stepButton

In RGBModel:
- redEventModel
- greenEventModel
- blueEventModel

In GaussianWavelengthSlider:
- slider

Partly wondering this, because I see this in RGBSlider:

```js
    // @public but only for together.js
    this.slider = hSlider;
```

Can @samreid or @jbphet comment, since they worked on instrumenting this sim.

**Comment by samreid** [comment]
No need to make things instance properties, tandem handles closure vars nicely.  Also, color vision is already instrumented and seems to be working nicely as well.  I removed the this.slider line and the sim runs without problems and I don't expect any together or phet-io issues.

**Comment by samreid** [comment]
Removed above, closing.
