### ISSUE TITLE
add visibility annotations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/color-vision#98]
In https://github.com/phetsims/tasks/issues/307, @aaronsamuel137 said:
> I'll try to do this for color-vision before I leave.

At 12/3/15 developer meeting, we decided to create this issue, and address it when the sim is instrumented for phet-io.

**Comment by ariel-phet** [comment]
@samreid see above comment. Is this sim already fully instrumented? If so, has this issue been addressed?

**Comment by samreid** [comment]
Apparently this work was already done in #97, closing as duplicate.
